"""Initial schema

Revision ID: 814d1ff83831
Revises: 
Create Date: 2026-08-06 12:59:17.166351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814d1ff83831'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_organization_id'), 'organizations', ['organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_organization_members_membership_id'), 'organization_members', ['membership_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lead_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_activity_id'), 'activities', ['activity_id'], unique=False)
    op.create_table('corrections',
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_text', sa.Text(), nullable=True),
    sa.Column('after_text', sa.Text(), nullable=True),
    sa.Column('location_hint', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_index(op.f('ix_corrections_correction_id'), 'corrections', ['correction_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_edited_by', sa.Integer(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_by', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checked_out_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.version_id'], use_alter=True),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_table('project_members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_project_members_member_id'), 'project_members', ['member_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index(op.f('ix_review_queue_queue_id'), 'review_queue', ['queue_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_workflow_history_history_id'), 'workflow_history', ['history_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('version_label', sa.String(), nullable=True),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('minor', sa.Integer(), nullable=True),
    sa.Column('patch', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_document_versions_version_id'), 'document_versions', ['version_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('arbitrations',
    sa.Column('arbitration_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('candidate_a_version', sa.Integer(), nullable=True),
    sa.Column('candidate_b_version', sa.Integer(), nullable=True),
    sa.Column('preferred_version', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved_a', sa.Boolean(), nullable=True),
    sa.Column('resolved_b', sa.Boolean(), nullable=True),
    sa.Column('total_tracked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_a_version'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['candidate_b_version'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['preferred_version'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('arbitration_id')
    )
    op.create_index(op.f('ix_arbitrations_arbitration_id'), 'arbitrations', ['arbitration_id'], unique=False)
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('section_path', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_index(op.f('ix_blocks_block_id'), 'blocks', ['block_id'], unique=False)
    op.create_index(op.f('ix_blocks_content_hash'), 'blocks', ['content_hash'], unique=False)
    op.create_table('reconciliation_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('json_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['json_file_id'], ['report_files.file_id'], use_alter=True),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['report_files.file_id'], use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reconciliation_reports_report_id'), 'reconciliation_reports', ['report_id'], unique=False)
    op.create_table('version_diffs',
    sa.Column('diff_id', sa.Integer(), nullable=False),
    sa.Column('from_version_id', sa.Integer(), nullable=False),
    sa.Column('to_version_id', sa.Integer(), nullable=False),
    sa.Column('diff_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_version_id'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('diff_id')
    )
    op.create_index(op.f('ix_version_diffs_diff_id'), 'version_diffs', ['diff_id'], unique=False)
    op.create_table('change_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_version_id', sa.Integer(), nullable=True),
    sa.Column('to_version_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('from_block_id', sa.Integer(), nullable=True),
    sa.Column('to_block_id', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['from_version_id'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['to_block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_change_events_event_id'), 'change_events', ['event_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_table('correction_states',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_block_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.correction_id'], ),
    sa.ForeignKeyConstraint(['matched_block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_correction_states_state_id'), 'correction_states', ['state_id'], unique=False)
    op.create_table('report_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reconciliation_reports.report_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_report_files_file_id'), 'report_files', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_files_file_id'), table_name='report_files')
    op.drop_table('report_files')
    op.drop_index(op.f('ix_correction_states_state_id'), table_name='correction_states')
    op.drop_table('correction_states')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_change_events_event_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_version_diffs_diff_id'), table_name='version_diffs')
    op.drop_table('version_diffs')
    op.drop_index(op.f('ix_reconciliation_reports_report_id'), table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.drop_index(op.f('ix_blocks_content_hash'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_arbitrations_arbitration_id'), table_name='arbitrations')
    op.drop_table('arbitrations')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_document_versions_version_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_workflow_history_history_id'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_review_queue_queue_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_project_members_member_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_corrections_correction_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_activities_activity_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organization_members_membership_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_organization_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
